SAIS/SAIS/WebApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name = 'register'),
	url(r'^register/submit$', views.formRegister, name='submitForm'),
]

SAIS/mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SAIS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^WebApp/', include('WebApp.urls', namespace='WebApp')),
    	]

WebApp/urls.py
from django.conf.urls import url
from WebApp.views import *	
from . import views

urlpatterns = [
	url(r'^$', IndexView.as_view(), name='index'),
	url(r'^register$', RegistrationView.as_view(), name = 'register'),
	url(r'^login$', LoginView.as_view(), name = 'login'),
	url(r'^profile$', StudentView.as_view(), name = 'viewIndexS'),
	url(r'^edit$', EditView.as_view(), name = 'edit'),
	url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/WebApp/login'}, name='logout'),
	url(r'^enlist$', StudentEnlist.as_view(), name = 'enlist'),
	url(r'^schedule$', StudentViewSchedule.as_view(), name='schedule'),
	url(r'^account$', StudentViewAccount.as_view(), name='account')
]

SAIS/SAIS/WebApp/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
	fname = models.CharField(max_length=20, null=True, blank = True)
	mname = models.CharField(max_length=20, null=True, blank = True)
	lname = models.CharField(max_length=20, null=True, blank = True)
	user_id = models.IntegerField(null=True, blank = True)
	student_id = models.CharField(max_length=10, null=True, blank = True) #PK
	address = models.CharField(max_length = 10, null=True, blank = True)

	def __str__(self):
		return str(self.student_id)

class SchoolInfo(models.Model):
	student_id = models.ForeignKey('Student')
	course_id = models.CharField(max_length=20, null=True, blank=True) 
	year = models.IntegerField(null=True, blank = True)
	sts_code = models.CharField(max_length=20, null=True, blank=True)

class Course(models.Model):
	course_id = models.ForeignKey('SchoolInfo')
	course = models.CharField(max_length = 20, null=True, blank = True)

class Subjects(models.Model):
	subject_code = models.CharField(max_length=20, null=True, blank=True)
	cluster_code = models.CharField(max_length=20, null=True, blank=True)
	prof_id = models.CharField(max_length=20, null=True, blank=True)
	schedule_id = models.IntegerField(null=True, blank=True)

class Schedule(models.Model):
	schedule_id = models.ForeignKey('Subjects')
	day = models.CharField(max_length=10, null=True, blank=True)
	time = models.CharField(max_length=20, null=True, blank=True)

class STSBracket(models.Model):
	sts_code = models.ForeignKey('SchoolInfo')
	subsidy = models.IntegerField(null=True, blank=True)

class Account(models.Model):
	student_id = models.ForeignKey('SchoolInfo')
	transactions = models.CharField(max_length=20, null=True, blank=True)#Payment or Loan#
	amount = models.FloatField(null=True, blank=True)
	

WebApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
	fname = models.CharField(max_length=20, null=True, blank = True)
	mname = models.CharField(max_length=20, null=True, blank = True)
	lname = models.CharField(max_length=20, null=True, blank = True)
	user_id = models.OneToOneField(User, null=True, blank=True)
	student_id = models.CharField(max_length=10, null=True, blank = True) #PK
	address = models.CharField(max_length = 10, null=True, blank = True)
	gender = models.CharField(max_length = 10, null=True, blank = True)
	maritalstatus = models.CharField(max_length = 15, null=True, blank = True)
	email = models.CharField(max_length=30 , null = True, blank = True)

	def __str__(self):
		return str(self.student_id) + " : " + str(self.lname)

class SchoolInfo(models.Model):
	student_id = models.ForeignKey('Student')
	course = models.CharField(max_length = 20, null=True, blank = True)
	year = models.IntegerField(null=True, blank = True)
	sts_code = models.CharField(max_length=20, null=True, blank=True)

	def __str__(self):
		return str(self.student_id) + " Info"

class Subjects(models.Model):
	subject_code = models.CharField(max_length=20, null=True, blank=True)
	cluster_code = models.CharField(max_length=20, null=True, blank=True)
	prof_id = models.CharField(max_length=20, null=True, blank=True)

	def __str__(self):
		return str(self.subject_code)

class Schedule(models.Model):
	subject_id = models.ForeignKey('Subjects')
	day = models.CharField(max_length=10, null=True, blank=True)
	time = models.CharField(max_length=20, null=True, blank=True)

	def __str__(self):
		return str(self.subject_id) + " : " +str(self.day) +" "+ str(self.time) 

class Enrolled(models.Model):
	student_id = models.ForeignKey('Student')
	subject_code = models.ForeignKey('Subjects')

class Account(models.Model):
	student_id = models.ForeignKey('SchoolInfo')
	transactions = models.CharField(max_length=20, null=True, blank=True)#Payment or Loan#
	amount = models.FloatField(null=True, blank=True)
	

SAIS/SAIS/WebApp/forms.py
from django.forms import ModelForm
from WebApp.models import Student

class AddStudentForm(ModelForm):
	class Meta:
		model = Student
		fields = ['fname', 'mname', 'lname', 'student_id', 'address']

WebApp/forms.py
from django.forms import ModelForm
from WebApp.models import Student
from WebApp.models import SchoolInfo

class AddStudentForm(ModelForm):
	class Meta:
		model = Student
		fields = ['fname', 'mname', 'lname', 'student_id', 'address']

class AddSchoolInfoForm(ModelForm):
	class Meta:
		model = SchoolInfo
		fields = ['course','year', 'sts_code']

SAIS/SAIS/WebApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import forms

def index(request):
	return render(request, 'main.html')

def register(request):
	return render(request, 'register.html')

def formRegister(request):
	
	newUser = forms.AddStudentForm(request.POST)
	newUser.save()

	return render(request, 'main.html')

# Create your views here.

WebApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View, DetailView
from WebApp.models import Student, SchoolInfo, Subjects
from django.template import Context

class IndexView(View):
	
	def get(self, request):	
		return render(self.request, 'main.html')

class StudentViewSchedule(View):

	def get(self, request):
		context = {}
		context['user'] = request.user.first_name
		return render(self.request,'indexStudent-Schedule.html',context=context)

class StudentViewAccount(View):

	def get(self, request):
		context = {}
		context['user'] = request.user.first_name
		return render(self.request,'indexStudent-Account.html',context=context)

class StudentEnlist(View):

	def get(self, request):
		context = {}
		context['user'] = request.user.first_name
		return render(self.request, 'indexStudent-Enlist.html', context=context)


	def post(self, request):

		keyword = request.POST.get('searchbox')
		print("Keyword is: " + keyword)
		context = {}
		context['subjectcode'] = Subjects.objects.filter(subject_code__icontains=keyword)
		return render(self.request,'indexStudent-Enlist.html',context=context)

class StudentView(View):
	def get(self, request):
		if not request.user.is_authenticated():
			return render(self.request, 'login.html')
		else:
			 student_object = Student.objects.filter(user_id=request.user)
			 schoolinfo_object = SchoolInfo.objects.filter(student_id=student_object)
			
		   
			 dictionary = {
		    	'firstname': student_object.get().fname,
		    	'middlename': student_object.get().mname,
		    	'lastname': student_object.get().lname,
		    	'address': student_object.get().address,
		    	'gender': student_object.get().gender,
		    	'maritalstatus': student_object.get().maritalstatus,
		    	'student_id': student_object.get().student_id,
		    	'email': student_object.get().email,
		    	'course': schoolinfo_object.get().course,
		    	'year': schoolinfo_object.get().year,
		    	'sts_code': schoolinfo_object.get().sts_code,
		    	'user': request.user.first_name,
		    	}
		
		return render(self.request,'indexStudent-Profile.html',dictionary)

class LoginView(View):
	"""docstring for LoginView"""
	def get(self, request):
		if not request.user.is_authenticated():
			return render(self.request, 'login.html')
		else:
			return render(self.request, 'indexStudent-Profile.html')

	def post(self, request):
		user = User()
		username = request.POST.get('student_id')
		password = request.POST.get('password')
		user = authenticate(username = username, password =password)
		if user is not None:
		    # the password verified for the user		
		  		login(request, user)
		  		return HttpResponseRedirect('../WebApp/profile') 
		 
		else:  # Return an 'invalid login' error message.
			print("The username and password were incorrect.")
			return render(self.request, 'login.html')

class LogoutView(View):
	def get(self, request):
		return redirect('WebApp:logout')	

	def post(self, request):
		logout(request, user)

class RegistrationView(View):
	
	def get(self, request):
		return render(self.request, 'register.html')

	def post(self, request):
		student = Student()
		studentInfo = SchoolInfo()
		
		student.fname = request.POST['fname']
		student.mname = request.POST['mname']
		student.lname = request.POST['lname']
		student.student_id = request.POST['student_id']
		student.address = request.POST['address']
		student.gender = request.POST['gender']
		student.maritalstatus = request.POST['maritalstatus']
		student.email = request.POST['email']
		student.save()

		studentInfo.student_id = student
		studentInfo.course = request.POST['course']
		studentInfo.year = request.POST['year']
		studentInfo.sts_code = request.POST['sts_code']
		studentInfo.save()

		user = User.objects.create_user(student.student_id, student.email, request.POST['password'])
		
		user.last_name = student.lname
		user.first_name = student.fname
		user.save()
		print(user.username)

		student.user_id = user;
		student.save()

		return render(self.request, 'login.html')

class SearchClassView(View):

	def get(self, request):
		return render(self.request, 'AddClass.html')

	def post(self, request):
		keyword = request.POST.get('searchbox')
		print("Keyword is: " + keyword)
		context = {}
		context['subjectcode'] = Subjects.objects.filter(subject_code__icontains=keyword)
		return render(self.request,'AddClass.html',context=context)


class EditView(View):
	
	def get(self, request):
		if request.user.is_authenticated():
		    student_object = Student.objects.filter(user_id=request.user)
		    schoolinfo_object = SchoolInfo.objects.filter(student_id=student_object)
		    dictionary = {
		    	'firstname': student_object.get().fname,
		    	'middlename': student_object.get().mname,
		    	'lastname': student_object.get().lname,
		    	'address': student_object.get().address,
		    	'gender': student_object.get().gender,
		    	'maritalstatus': student_object.get().maritalstatus,
		    	'student_id': student_object.get().student_id,
		    	'email': student_object.get().email,
		    	'course': schoolinfo_object.get().course,
		    	'year': schoolinfo_object.get().year,
		    	'sts_code': schoolinfo_object.get().sts_code,
		    	'user': request.user.first_name,

		    	}
		    return render(self.request, 'EditProfile.html', dictionary)
		else:
			return render(self.request, 'login.html')

	def post(self, request):

		#Entry.objects.filter(pub_date__year=2007).update(headline='Everything is the same')
		student_objects = Student.objects.filter(user_id=request.user)
		schoolinfo_objects = SchoolInfo.objects.filter(student_id=student_objects)
		print("I AM HERE!!" + student_objects.get().lname)
		firstname = request.POST['fname']
		middlename = request.POST['mname']
		lastname = request.POST['lname']
		address = request.POST['address']
		gender = request.POST['gender']
		maritalstatus = request.POST['maritalstatus']
		email = request.POST['email']
		course = request.POST['course']
		year = request.POST['year']

		student_objects.update(fname = firstname)
		student_objects.update(mname = middlename)
		student_objects.update(lname = lastname)
		student_objects.update(address = address)
		student_objects.update(gender = gender)
		student_objects.update(maritalstatus = maritalstatus)
		
		student_objects.update(email = email)
		schoolinfo_objects.update(course=course)
		schoolinfo_objects.update(year=year)

		return HttpResponseRedirect('../WebApp/profile') 

	
		

WebApp/templates/AddClass.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Class</title>
</head>
<body>
<form  action="{% url 'WebApp:addclass' %}" method="POST" id="addClassForm">
	{% csrf_token %} 
	ADD CLASS: <br><br>
	Search: <input type="text" name="searchbox">
	<input type="submit" name="searchClass">
	<br><br>
	Retrieved classes: 
	<br><br>
		{{ subjectcode }}
		<br><br>
 
 	Add specific class: <input type="text" name="addthisclass">
 	<input type="submit" name="addthisclass" value="Add">


</form>
</body>
</html>

WebApp/templates/EditProfile.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>SAIS - PROFILE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head> 

<body>

	<nav class="navbar navbar-default navbar-fixed-top">
	  	<div class="container-fluid">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">
		    		<img alt="Brand" src="{% static 'WebApp/img/uplogo.png' %}" width="50px" height="50px">
		    	</a>
		    	<p class="navbar-text">Student Profile</p>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		      <ul class="nav navbar-nav navbar-right">
		      	<li><p class="navbar-text-smaller">Welcome,</p></li>
		        <li><p class="navbar-text-small">{{user}}</p></li>


		        
		        <li>
		        	<form class="navbar-form navbar-left" action="{% url 'WebApp:logout' %}">
		        		<button type="submit" class="btn btn-danger navbar-btn">Log Out</button>
		        	</form>
		        </li>

		      </ul>
		    </div><!-- /.navbar-collapse -->
	  	</div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li class="active"><a href="{% url 'WebApp:viewIndexS' %}">Profile</a></li>
				<li><a href="{% url 'WebApp:schedule' %}">Schedule</a></li>
				<li><a href="{% url 'WebApp:account' %}">Accountability</a></li>
				<li><a href="{% url 'WebApp:enlist' %}">Enlist Subjects</a></li>

			</ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
									<div class="jumbotron">
									<h1>Edit Information</h1>
								<form action="{% url 'WebApp:edit' %}" method="POST">
			{% csrf_token %}
				<ul class="nav no-list">
					<label>Student Number: </label>
					<input class="form-control" type="text" id="student_id" name="student_id" value="{{ student_id }}" disabled="true">
					 <br><label>First Name: </label>
					<input class="form-control" type="text" id="fname" name="fname" value="{{ firstname }}"> 
					 <br><label>Middle Name: </label>
					<input class="form-control" type="text" id="mname" name="mname" value="{{ middlename }}"> 
					 <br><label>Last Name: </label>
					<input class="form-control" type="text" name="lname" id="lname" value="{{ lastname }}"> 
					 <br><label>Address: </label>
					<input class="form-control" type="text" name="address" id="address" value="{{address}}"> 
					 <br><label>Email Address: </label>
					<input class="form-control" type="text" name="email" id="email" value="{{ email }}"> 
					 <br><label>Gender: </label>
					<input class="form-control" type="text" name="gender" id="gender" value="{{ gender }}"> 
					 <br><label>Marital Status: </label>
					<input class="form-control" type="text" name="maritalstatus" id="maritalstatus" value="{{ maritalstatus }}"> 
				</ul>
				<br>
				<br>
				<ul class="nav no-list">
					 <br><label>Course: 
					<input class="form-control" type="text" name="course" id="course" value="{{ course }}"> 
					 <br><label>Year: 
					<input class="form-control" type="text" name="year" id="year" value="{{ year }}"> 
					 <br><label>STS Bracket: 
					<input class="form-control" type="text" name="sts_code" id="sts_code" value="{{ sts_code }}" disabled="true"> 
				</ul>
				<br>
				<br>

				<button type="submit" name="register" class="btn btn-default">Submit</button>
			</form>

							</div>
		</div>
	</div>
</body>
</html>

WebApp/templates/indexStudent-Account.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>SAIS - ACCOUNTABILITY</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head> 

<body>

	<nav class="navbar navbar-default navbar-fixed">
	  	<div class="container-fluid">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">
		    		<img alt="Brand" src="{% static 'WebApp/img/uplogo.png' %}" width="50px" height="50px">
		    	</a>
		    	<p class="navbar-text">Student Profile</p>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		      <ul class="nav navbar-nav navbar-right">
		      	<li><p class="navbar-text-smaller">Welcome,</p></li>
		        <li><p class="navbar-text-small">{{user}}</p></li>
		        
		        <li>
		        	<form class="navbar-form navbar-left" action="{% url 'WebApp:logout' %}">
		        		<button type="submit" class="btn btn-danger navbar-btn">Log Out</button>
		        	</form>
		        </li>

		      </ul>
		    </div><!-- /.navbar-collapse -->
	  	</div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li><a href="{% url 'WebApp:viewIndexS' %}">Profile</a></li>
				<li><a href="{% url 'WebApp:schedule' %}">Schedule</a></li>
				<li class="active"><a href="{% url 'WebApp:account' %}">Accountability</a></li>
				<li><a href="{% url 'WebApp:enlist' %}">Enlist Subjects</a></li>

			</ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<div class="jumbotron">
					  <h1>Accountability</h1>
					  <li>You are not accounted for anything</li><br>
					  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
				</div>
		</div>
	</div>

	


</body>
</html>

WebApp/templates/indexStudent-Enlist.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>SAIS - ENLIST</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head> 

<body>

	<nav class="navbar navbar-default navbar-fixed">
	  	<div class="container-fluid">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">
		    		<img alt="Brand" src="{% static 'WebApp/img/uplogo.png' %}" width="50px" height="50px">
		    	</a>
		    	<p class="navbar-text">Student Profile</p>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		      <ul class="nav navbar-nav navbar-right">
		      	<li><p class="navbar-text-smaller">Welcome,</p></li>
		        <li><p class="navbar-text-small">{{user}}</p></li>
		        
		        <li>
		        	<form class="navbar-form navbar-left" action="{% url 'WebApp:logout' %}">
		        		<button type="submit" class="btn btn-danger navbar-btn">Log Out</button>
		        	</form>
		        </li>

		      </ul>
		    </div><!-- /.navbar-collapse -->
	  	</div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li><a href="{% url 'WebApp:viewIndexS' %}">Profile</a></li>
				<li><a href="{% url 'WebApp:schedule' %}">Schedule</a></li>
				<li><a href="{% url 'WebApp:account' %}">Accountability</a></li>
				<li class="active"><a href="{% url 'WebApp:enlist' %}">Enlist Subjects</a></li>

			</ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<div class="jumbotron">
					  <h1>ADD CLASS:</h1>

					  <form  action="{% url 'WebApp:enlist' %}" method="POST" id="enlistClassForm">
						{% csrf_token %} 
						Search: <input type="text" name="searchbox">
						<input type="submit" name="searchClass">
						<br><br>
						Retrieved classes: 
						<br><br>
							{{ subjectcode }}
							<br><br>
					 
					 	Add specific class: <input type="text" name="addthisclass">
					 	<input type="submit" name="addthisclass" value="Add">


					</form>
				</div>
		</div>
	</div>

	


</body> 

</html>

WebApp/templates/indexStudent-Profile.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>SAIS - PROFILE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head> 

<body>

	<nav class="navbar navbar-default navbar-fixed">
	  	<div class="container-fluid">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">
		    		<img alt="Brand" src="{% static 'WebApp/img/uplogo.png' %}" width="50px" height="50px">
		    	</a>
		    	<p class="navbar-text">Student Profile</p>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		      <ul class="nav navbar-nav navbar-right">
		      	<li><p class="navbar-text-smaller">Welcome,</p></li>
		        <li><p class="navbar-text-small">{{user}}</p></li>


		        
		        <li>
		        	<form class="navbar-form navbar-left" action="{% url 'WebApp:logout' %}">
		        		<button type="submit" class="btn btn-danger navbar-btn">Log Out</button>
		        	</form>
		        </li>

		      </ul>
		    </div><!-- /.navbar-collapse -->
	  	</div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li class="active"><a href="{% url 'WebApp:viewIndexS' %}">Profile</a></li>
				<li><a href="{% url 'WebApp:schedule' %}">Schedule</a></li>
				<li><a href="{% url 'WebApp:account' %}">Accountability</a></li>
				<li><a href="{% url 'WebApp:enlist' %}">Enlist Subjects</a></li>

			</ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<div class="jumbotron">
				  <h1>Student Information</h1>
				  <li>Name: {{firstname}} {{middlename}} {{lastname}}</li><br>
				  <li>Gender: {{gender}}</li><br>
				  <li>Student ID: {{student_id}}</li><br>
				  <li>Course and Year: {{course}} - {{year}}</li><br>
				  <li>STS Bracket: {{sts_code}}</li><br>
				  <li>Address: {{address}}</li><br>
				  <li>Marital Status: {{maritalstatus}}</li><br>
				  <li>Email: {{email}}</li><br>
				  <a class="btn btn-primary btn-lg" href="{% url 'WebApp:edit' %}" role="button">Edit Profile</a>
				</div>		
		</div>
	</div>

	


</body>
</html>

WebApp/templates/indexStudent-Schedule.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>SAIS - SCHEDULE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head> 

<body>

	<nav class="navbar navbar-default navbar-fixed">
	  	<div class="container-fluid">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">
		    		<img alt="Brand" src="{% static 'WebApp/img/uplogo.png' %}" width="50px" height="50px">
		    	</a>
		    	<p class="navbar-text">Student Profile</p>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		      <ul class="nav navbar-nav navbar-right">
		      	<li><p class="navbar-text-smaller">Welcome,</p></li>
		        <li><p class="navbar-text-small">{{user}}</p></li>
		        
		        <li>
		        	<form class="navbar-form navbar-left" action="{% url 'WebApp:logout' %}">
		        		<button type="submit" class="btn btn-danger navbar-btn">Log Out</button>
		        	</form>
		        </li>

		      </ul>
		    </div><!-- /.navbar-collapse -->
	  	</div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li><a href="{% url 'WebApp:viewIndexS' %}">Profile</a></li>
				<li class="active"><a href="{% url 'WebApp:schedule' %}">Schedule</a></li>
				<li><a href="{% url 'WebApp:account' %}">Accountability</a></li>
				<li><a href="{% url 'WebApp:enlist' %}">Enlist Subjects</a></li>

			</ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<div class="jumbotron">
							  <h1>Schedule</h1>
							  <li>You are not enrolled in any class yet.</li><br>
							  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
							</div>
		</div>
	</div>

	


</body>
</html>

WebApp/templates/main.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
	<title>Student Access Information System</title>
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'WebApp/css/bootstrap.css' %}">
</head>

<body>
	<div id = header>
	<div class="container-fluid">
	  <div class="row">
			<div class="col-xs-10 col-md-1">
				<img src="{% static 'WebApp/img/uplogo.png' %}" width="100px" height="100px">
			</div>
			<div class="col-xs-10 col-md-9">
				<h2>Student Access Information System</h2>
				<p class = header>University of the Philippines Cebu</p>

			</div>
			<div class="col-xs-6 col-md-2 mainbuttons">
				<form action="{% url 'WebApp:register' %}" id="register">
				{% csrf_token %}
					<button type="submit" class="btn btn-default btn-block">Register</button>
				</form>
				<br>
				<form action="{% url 'WebApp:login' %}" id="login">
				{% csrf_token %}
					<button type="submit" class="btn btn-success btn-block">Log In</button>
				</form>
			
			</div>
	  </div>
	</div>

	</div>

	<div class="jumbotron">
		<h1>WELCOME</h1>
		<p>UPDATES WILL BE INSERTED</p>
		<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
	</div>

</body>
</html>